In [148]:
# dic1 = {key:volume}

dict1 = {1:'A', 2:'B', 3:'C'}
len(dict1)

3

In [3]:
dict1[3]

'C'

In [4]:
dict1[2]

'B'

In [5]:
Classroom = {'A':56, 'B':84, 'C':97, 'D':56, 'E':100, 'F':81}

In [6]:
Classroom

{'A': 56, 'B': 84, 'C': 97, 'D': 56, 'E': 100, 'F': 81}

In [7]:
Classroom['C']

97

In [9]:
Classroom_LIST = [['A',56], ['B',84], ['C',97], ['D',56], ['E',100], ['F',81]]
Classroom_LIST

[['A', 56], ['B', 84], ['C', 97], ['D', 56], ['E', 100], ['F', 81]]

In [12]:
Classroom = {'A':5['P','C','M'], 'B':84, 'C':97, 'D':56, 'E':100, 'F':81}

<>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
C:\Users\88017\AppData\Local\Temp\ipykernel_8656\3413526001.py:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  Classroom = {'A':5['P','C','M'], 'B':84, 'C':97, 'D':56, 'E':100, 'F':81}


TypeError: 'int' object is not subscriptable

In [11]:
Classroom

{'A': 56, 'B': 84, 'C': 97, 'D': 56, 'E': 100, 'F': 81}

In [15]:
Classroom = {'A1':['P','C','M'], 'B':84, 'C':97, 'D':56, 'E':100, 'F':81, 'A2': 63}

In [16]:
Classroom

{'A1': ['P', 'C', 'M'], 'B': 84, 'C': 97, 'D': 56, 'E': 100, 'F': 81, 'A2': 63}

In [18]:
Classroom = {'A1':{'P':76,'C':97,'M':95}, 'B':84, 'C':97, 'D':56, 'E':100, 'F':81, 'A2': 63}

In [19]:
Classroom

{'A1': {'P': 76, 'C': 97, 'M': 95},
 'B': 84,
 'C': 97,
 'D': 56,
 'E': 100,
 'F': 81,
 'A2': 63}

In [20]:
Classroom = {'A1':95, 'B':84, 'C':97, 'D':56, 'E':100, 'F':81, 'A2': 63}

Classroom.items()

dict_items([('A1', 95), ('B', 84), ('C', 97), ('D', 56), ('E', 100), ('F', 81), ('A2', 63)])

In [26]:
Classroom = {'A1':95, 'B':84, 'C':97, 'D':56, 'E':100, 'F':81, 'A2': 63}

Classroom.values()

dict_values([95, 84, 97, 56, 100, 81, 63])

In [54]:
Classroom = {'A1':95, 'B':84, 'C':97, 'D':56, 'E':100, 'F':81, 'A2': 63}
import numpy as np
a = np.array(list(Classroom.values()))
np.where(a >90, 1, 0)

array([1, 0, 1, 0, 1, 0, 0])

In [48]:
Classroom = {'A1':95, 'B':84, 'C':97, 'D':99, 'E':100, 'F':81, 'A2': 96}
import numpy as np
a = np.array(list(Classroom.values()))
np.where(a >90, 1, 0)

array([1, 0, 1, 1, 1, 0, 1])

In [49]:
for i in a:
    if i>90:
        for j in Classroom:
            if Classroom[j]== i:
                print(j)

A1
C
D
E
A2


In [35]:
for i in a:
    if i>90:
        for j in Classroom:
            if Classroom[j]== i:
                print(j)
                break

A1
C
D
E
A2


In [36]:
a = np.where(a >90, 1, 0)
a

array([1, 0, 1, 1, 1, 0, 1])

In [55]:
# empty range
print(list(range(0)))

# using range(stop)
print(list(range(12)))

# using range(start, stop)
print(list(range(1, 15)))

[]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


In [56]:
a=np.where(a >90, 1, 0)
a=list(a)
for i in range(len(a)):
    if a[i]==1:
        print(list(Classroom.keys())[i])

A1
C
E


In [57]:
Classroom = {'A1':{'P':76,'C':97,'M':95}, 
             'B':{'P':53,'C':99,'M':34}, 
             'C':{'P':67,'C':94,'M':41}, 
             'D':{'P':12,'C':97,'M':78},
             'E':{'P':96,'C':52,'M':90}, 
             'F':{'P':71,'C':23,'M':99}, 
             'A2':{'P':45,'C':52,'M':97}}

In [58]:
Classroom['A1']

{'P': 76, 'C': 97, 'M': 95}

In [59]:
Classroom['A1']['C']

97

In [70]:
Classroom['F']['M']

99

In [73]:
def find_students(marks):
    students = []
    for student, mark in marks.items():
        if mark > 90:
            students.append(student)
            return students
        
        #sample data
        
        marks = {
            "student1": 97,
            "student2": 64,
            "student3": 92,
            "student4": 26
            
        }
        
        print("Students with marks greater than 90:", find_students(marks))

In [74]:
Classroom['D']['M']

78

In [75]:
Classroom

{'A1': {'P': 76, 'C': 97, 'M': 95},
 'B': {'P': 53, 'C': 99, 'M': 34},
 'C': {'P': 67, 'C': 94, 'M': 41},
 'D': {'P': 12, 'C': 97, 'M': 78},
 'E': {'P': 96, 'C': 52, 'M': 90},
 'F': {'P': 71, 'C': 23, 'M': 99},
 'A2': {'P': 45, 'C': 52, 'M': 97}}

In [76]:
Classroom.keys()

dict_keys(['A1', 'B', 'C', 'D', 'E', 'F', 'A2'])

In [77]:
Classroom.values()

dict_values([{'P': 76, 'C': 97, 'M': 95}, {'P': 53, 'C': 99, 'M': 34}, {'P': 67, 'C': 94, 'M': 41}, {'P': 12, 'C': 97, 'M': 78}, {'P': 96, 'C': 52, 'M': 90}, {'P': 71, 'C': 23, 'M': 99}, {'P': 45, 'C': 52, 'M': 97}])

In [78]:
Classroom['A1'].keys()

dict_keys(['P', 'C', 'M'])

In [79]:
Classroom['C'].values()

dict_values([67, 94, 41])

In [80]:
Classroom['A1'].items()

dict_items([('P', 76), ('C', 97), ('M', 95)])

In [81]:
Classroom = {'A1':{'P':76,'C':97,'M':95}, 
             'B':{'P':53,'C':99,'M':34}, 
             'C':{'P':67,'C':94,'M':41}, 
             'D':{'P':12,'C':97,'M':78},
             'E':{'P':96,'C':52,'M':90}, 
             'F':{'P':71,'C':23,'M':99}, 
             'A2':['P','C','M']}

In [82]:
Classroom

{'A1': {'P': 76, 'C': 97, 'M': 95},
 'B': {'P': 53, 'C': 99, 'M': 34},
 'C': {'P': 67, 'C': 94, 'M': 41},
 'D': {'P': 12, 'C': 97, 'M': 78},
 'E': {'P': 96, 'C': 52, 'M': 90},
 'F': {'P': 71, 'C': 23, 'M': 99},
 'A2': ['P', 'C', 'M']}

In [83]:
Classroom['A2']

['P', 'C', 'M']

In [84]:
Classroom['A2'][0]

'P'

In [85]:
Classroom = {'A1':{'P':76,'C':97,'M':95}, 
             'B':{'P':53,'C':99,'M':34}, 
             'C':{'P':67,'C':94,'M':41}, 
             'D':{'P':12,'C':97,'M':78},
             'E':{'P':96,'C':52,'M':90}, 
             'F':{'P':71,'C':23,'M':99}, 
             'A2':['P','C','M']}

In [86]:
del Classroom['C']

In [87]:
Classroom

{'A1': {'P': 76, 'C': 97, 'M': 95},
 'B': {'P': 53, 'C': 99, 'M': 34},
 'D': {'P': 12, 'C': 97, 'M': 78},
 'E': {'P': 96, 'C': 52, 'M': 90},
 'F': {'P': 71, 'C': 23, 'M': 99},
 'A2': ['P', 'C', 'M']}

In [88]:
Classroom['New']=89

In [92]:
Classroom

{'A1': {'P': 76, 'C': 97, 'M': 95},
 'B': {'P': 53, 'C': 99, 'M': 34},
 'D': {'P': 12, 'C': 97, 'M': 78},
 'E': {'P': 96, 'C': 52, 'M': 90},
 'F': {'P': 71, 'C': 23, 'M': 99},
 'A2': ['P', 'C', 'M'],
 'New': 89}

In [91]:
Classroom.update(marks)

{'A1': {'P': 76, 'C': 97, 'M': 95},
 'B': {'P': 53, 'C': 99, 'M': 34},
 'D': {'P': 12, 'C': 97, 'M': 78},
 'E': {'P': 96, 'C': 52, 'M': 90},
 'F': {'P': 71, 'C': 23, 'M': 99},
 'A2': ['P', 'C', 'M'],
 'New': 89}

In [127]:
Classroom

{'A1': {'P': 76, 'C': 97, 'M': 95},
 'B': {'P': 53, 'C': 99},
 'C': {'P': 67, 'C': 94, 'M': 41},
 'D': {'P': 12, 'C': 97, 'M': 78},
 'E': {'C': 52, 'M': 90},
 'F': {'P': 71, 'C': 23, 'M': 99},
 'A2': ['P', 'C', 'M']}

# crops list
crops = ['corn', 'wheat', 'cotton']

# Add 'cane' to the list
crops.append('cane')

print('Updated crops list: ', crops)

In [95]:
# create a list
even_numbers = [2, 4, 8]

# create another list
more_even_numers = [100, 400]

# add all elements of even_numbers to more_even_numbers
even_numbers.extend(more_even_numers)


print('List after extend():', even_numbers)

List after extend(): [2, 4, 8, 100, 400]


In [106]:
Classroom = {'A1':{'P':76,'C':97,'M':95}, 
             'B':{'P':53,'C':99,'M':34}, 
             'C':{'P':67,'C':94,'M':41}, 
             'D':{'P':12,'C':97,'M':78},
             'E':{'P':96,'C':52,'M':90}, 
             'F':{'P':71,'C':23,'M':99}, 
             'A2':['P','C','M']}

In [107]:
Classroom

{'A1': {'P': 76, 'C': 97, 'M': 95},
 'B': {'P': 53, 'C': 99, 'M': 34},
 'C': {'P': 67, 'C': 94, 'M': 41},
 'D': {'P': 12, 'C': 97, 'M': 78},
 'E': {'P': 96, 'C': 52, 'M': 90},
 'F': {'P': 71, 'C': 23, 'M': 99},
 'A2': ['P', 'C', 'M']}

In [108]:
del Classroom['E']['P']

In [117]:
Classroom

{'A1': {'P': 76, 'C': 97, 'M': 95},
 'B': {'P': 53, 'C': 99, 'M': 34},
 'C': {'P': 67, 'C': 94, 'M': 41},
 'D': {'P': 12, 'C': 97, 'M': 78},
 'E': {'C': 52, 'M': 90},
 'F': {'P': 71, 'C': 23, 'M': 99},
 'A2': ['P', 'C', 'M']}

In [118]:
del Classroom['B']['M']

In [122]:
Classroom

{'A1': {'P': 76, 'C': 97, 'M': 95},
 'B': {'P': 53, 'C': 99},
 'C': {'P': 67, 'C': 94, 'M': 41},
 'D': {'P': 12, 'C': 97, 'M': 78},
 'E': {'C': 52, 'M': 90},
 'F': {'P': 71, 'C': 23, 'M': 99},
 'A2': ['P', 'C', 'M']}

In [124]:
Classroom

{'A1': {'P': 76, 'C': 97, 'M': 95},
 'B': {'P': 53, 'C': 99},
 'C': {'P': 67, 'C': 94, 'M': 41},
 'D': {'P': 12, 'C': 97, 'M': 78},
 'E': {'C': 52, 'M': 90},
 'F': {'P': 71, 'C': 23, 'M': 99},
 'A2': ['P', 'C', 'M']}

In [135]:
# Conditional Statement

a = 6

b = 10

if a>b:
    
    print('a is greater')
    
if b>a: 
    
    print('b is greater')
    
if b>a: 
    
    print('b is greater')
    
if a==b:
        
    print('a and b are same')

b is greater
b is greater


In [136]:
# elif Conditional Statement will only be checked if previous condition is false.

if a>b:
    
    print('a is greater')
    
elif b>a: 
    
    print('b is greater')
    
elif b>a: 
    
    print('b is greater')
    
elif a==b:
        
    print('a and b are same')

b is greater


In [137]:
# Conditional Statement

a = 6

b = 10

if a>b:
    
    print('a is greater')
    
if b>a: 
    
    print('b is greater')
    
if a==b:
        
    print('a and b are same')

b is greater


In [138]:
# Conditional Statement

a = 6

b = 10

if a>b:
    
    print('a is greater')
    
elif b>a: 
    
    print('b is greater')
    
elif a==b:
        
    print('a and b are same')

b is greater


In [139]:
# Conditional Statement

a = 16

b = 10

if a>b:
    
    print('a is greater')
    
if b>a: 
    
    print('b is greater')
    
if a==b:
        
    print('a and b are same')

a is greater


In [140]:
# Conditional Statement

a = 16

b = 100

if a>b:
    
    print('a is greater')
    
if b>a: 
    
    print('b is greater')
    
if a==b:
        
    print('a and b are same')

b is greater


In [141]:
# Conditional Statement

a = 16

b = 100

if a>b:
    
    print('a is greater')
    
elif b>a: 
    
    print('b is greater')
    
elif a==b:
        
    print('a and b are same')

b is greater


In [143]:
a = 9

if a ==9:
    
    print('a is 9')
    
elif a==9:
        
    print('a is 9')

a is 9


In [144]:
a = 10

if a ==9:
    
    print('a is 9')
    
elif a==9:
        
    print('a is 9')

In [147]:
a = 10

if a ==9:
    
    print('a is 9')
    
elif a==9:
        
    print('a is 9')
    
else:
    
    print('a is not 9')

a is not 9


In [ ]:
if
if
if......

if
elif
elif.........

if
.
.
.
else

if
elif
.
.
.
.
elif
else

# Always starts with if
# Can end with elif or else
# elif can be found in the middle or last but else will always be at last

Start - if
Mid - elif, if
End - else, elif, if